spring:
  application:
    name: api
zuul:
    prefix: /api
    routes:
        demo:
            path: /**
            serviceId: demographics
                       
eureka: 
   client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance:
      preferIpAddress: true            
  
      
            