spring:
  application:
            name: Demo
spring:
  kafka:
    bootstrap-servers: localhost:9092
spring:
  kafka:
    consumer:
      group-id: jsa-group1
jsa:
  kafka:  
    topic:  jsa-springboot-topic
server:
  port: 0
eureka: 
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true